name: Updoc

on:
  workflow_dispatch: {}

jobs:
  publish-docs:
    uses: turkenf/uptest/.github/workflows/updoc.yml@main     
    secrets:
      UPBOUND_CI_PROD_BUCKET_SA: ${{ secrets.UPBOUND_CI_PROD_BUCKET_SA }}
